### PR TITLE
#112 Remove usage of FunctionConverters from Java 8 compat package

### PR DESCRIPTION
**Pull request by anilgursel**
Thanks for your pull request.  Please review the following guidelines.

- [x] Title includes issue id.
- [x] Description of the change added.
- [x] Commits are squashed.
- [ ] Tests added.
- [ ] Documentation added/updated.
- [x] Also please review [CONTRIBUTING.md](https://github.com/paypal/squbs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by anilgursel** [comment]
I have basically done a search for `scala.compat.java8` in the code base and checked all the matches.  We have quite many `OptionConversters` and `FutureConverters` usage; however, no more `FunctionConverters`.

There is one more place we can do some improvement, please share your suggestions:

• https://github.com/paypal/squbs/blob/RELEASE-0.9.1/squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala#L35

```scala
uniqueIdMapper: Function[Context, Optional[Any]] = new Function[Context, Optional[Any]] {
    override def apply(t: Context): Optional[Any] = Optional.empty()
  }
```

• https://github.com/paypal/squbs/blob/master/squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/japi/CircuitBreakerSettings.scala#L34

```scala
cleanUp: Consumer[Out] = new Consumer[Out] {
    override def accept(t: Out): Unit = ()
  },
```

**Comment by akara** [comment]
I don't really see issues with tho code above. Yes, both of them make use of the Java 8 functional interfaces directly instead of closures. But these are in JAPI package so I see it as a legit use. Please let me know what issues you see here. Thanks!

**Comment by anilgursel** [comment]
I think it is ok, but IntelliJ is not happy.  I tried to use lambda style, but I could not make it happy.

**Comment by akara** [comment]
Here's how I made IntelliJ happy:

```scala
case class CircuitBreakerSettings[In, Out, Context] private[japi] (
  circuitBreakerState: CircuitBreakerState,
  fallback: Optional[Function[In, Try[Out]]] = Optional.empty[Function[In, Try[Out]]],
  cleanUp: Consumer[Out] = ((_: Out) => ()).asInstanceOf[Consumer[Out]],
  failureDecider: Optional[Function[Try[Out], Boolean]] = Optional.empty[Function[Try[Out], Boolean]],
  uniqueIdMapper: Function[Context, Optional[Any]] =
  ((_: Context) => Optional.empty()).asInstanceOf[Function[Context, Optional[Any]]]) {
```

**Comment by akara** [comment]
Compilation went through. Tests are running. I'm just waiting to check whether I'll fail any tests with this.

**Comment by akara** [comment]
Nope I take it back. I got a runtime exception. Looking further...

**Comment by akara** [comment]
OK. Looks like we're dealing with a compiler bug. While I agree this issues is not immediately an issue, we should get it resolved.

**Pull request merged**
