### PR TITLE
#737: Added and adapted to support Scala 2.13 and latest libs

### PR DESCRIPTION
**Pull request by akara**
Excluding Akka 2.6 support. That one is for #738.
Thanks for your pull request.  Please review the following guidelines.

- [x] Title includes issue id.
- [x] Description of the change added.
- [x] Commits are squashed.
- [x] Tests added.
- [ ] Documentation added/updated.
- [ ] Also please review [CONTRIBUTING.md](https://github.com/paypal/squbs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by akara** [comment]
@anilgursel @sebady @crankydillo kindly help review. I know it is a very large PR. There are several areas I had to work on to ensure minimal warnings on Scala 2.13 and Scala 3 going forward. We mainly have to upgrade certain API like `JavaConverter` to `scala.jdk.CollectionConverter` and use the compat module. A few other things have to be done. Most of it is mechanical. So the changes to the many files are pretty much are the same, except a few.

The Travis build for Scala 2.13 is still not working properly. I'll figure this out as I have time in the next couple days. Thanks a ton!

One thing after making this change is it makes me really appreciate all the great work we all have done on this project.

**Review by anilgursel — APPROVED** [review]

**Comment by akara** [comment]
@anilgursel sorry for bugging one more time. I was still getting all the tests to pass, and by making the change I dismissed your review. Could not find it any longer... strange! Can you please let me know what I missed?

**Comment by akara** [comment]
Tests are passing now (click on the checks) but the callback to GitHub might have been lost.

**Review by sebady — APPROVED** [review]
LGTM

**Pull request merged**
